version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "vite"
        versions: ["7.x"]
      - dependency-name: "@vitejs/*"
        versions: ["7.x"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
