name: infra
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
description: A minimal Kubernetes TypeScript Pulumi program
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-typescript
