{{- if .Values.web.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "plotarr.fullname" . }}-web
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "plotarr.web.labels" . | nindent 4 }}
spec:
  {{- if .Values.web.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.web.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.web.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.web.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plotarr.web.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "plotarr.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "plotarr.api.labels" . | nindent 4 }}
spec:
  {{- if .Values.api.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.api.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.api.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plotarr.api.selectorLabels" . | nindent 6 }}
{{- end }}
