apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plotarr.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "plotarr.api.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.api.secrets.jwtSecret | quote }}
  google-client-id: {{ .Values.api.secrets.googleClientId | quote }}
  db-host: {{ .Values.api.secrets.dbHost | quote }}
  db-user: {{ .Values.api.secrets.dbUser | quote }}
  db-password: {{ .Values.api.secrets.dbPassword | quote }}
  db-port: {{ .Values.api.env.dbPort | quote }}
  db-name: {{ .Values.api.env.dbName | quote }}
