name: infra
runtime:
  name: nodejs
  options:
    packagemanager: auto
main: bin/index.js
description: A minimal Kubernetes TypeScript Pulumi program
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-typescript
