import type { Dict } from "./types";

export const en: Dict = {
	nav: {
		plan: "Plan",
		features: "Features",
		community: "Community",
		pricing: "Pricing",
		planRoute: "Plan a route",
		home: "Home",
		docs: "Docs",
		github: "GitHub",
		star: "Star",
		readDocs: "Read docs",
	},
	hero: {
		chip: "Run · Cycle · Walk",
		headlineLines: [{ text: "Pin it." }, { text: "Plan it." }, { text: "Move.", accent: true }],
		body: "Drop pins. Get a route that actually follows the trail. Run it, ride it, walk it, then share it with anyone.",
		ctaPrimary: "Plan your first route",
		ctaSecondary: "See features",
		bullets: ["Free forever", "No account to plan", "GPX in & out"],
	},
	marquee: [
		"🏃 Sint-Amands loop · 31.8 km",
		"🚴 Forest gravel grind · 62 km",
		"🥾 Lippelobos out-and-back · 12 km",
		"🏃 River dawn run · 8.2 km",
		"🚴 Café-to-café cruise · 41 km",
		"🥾 Sunday slow walk · 4.1 km",
		"🏃 Hill repeats · 6 km",
		"🚴 Tour de Puurs · 84 km",
	],
	planner: {
		eyebrow: "Live demo · no signup",
		title: [{ text: "Drop pins. " }, { text: "Get a route.", accent: true }],
		body: "A tiny version of the real planner. Click anywhere on the map to add a waypoint, the path snaps along the way.",
		mode: "Mode",
		modes: { run: "Run", cycle: "Cycle", walk: "Walk" },
		total: "Total",
		computedLive: "computed live",
		timeLabel: "time",
		openInApp: "Open in app",
		hint: "tip: tap and hold a pin to drag in the real app",
		clickHint: "click to add waypoint",
		reset: "Reset",
		waypoints: "waypoints",
	},
	mapStyles: {
		eyebrow: "Styles & themes",
		title: [{ text: "One route. " }, { text: "Any map.", accent: true }],
		body: "Streets for the city, outdoors for contour lines and trails, satellite for checking whether that gravel is actually gravel. And every style has a dark theme for planning after sunset.",
		items: [
			{ key: "streets", name: "Streets", desc: "Crisp and familiar" },
			{ key: "outdoors", name: "Outdoors", desc: "Contours, trails, terrain" },
			{ key: "satellite", name: "Satellite", desc: "See what's really there" },
			{ key: "dark", name: "Dark theme", desc: "Any style, lights off" },
		],
	},
	outside: {
		eyebrow: "Take it outside",
		title: [{ text: "Plan at your desk. " }, { text: "Follow it on the road.", accent: true }],
		body: "The same planner works on your phone, so the route you plotted on Sunday evening is in your pocket on Monday morning. And your routes are never locked in.",
		bullets: [
			"Works as an app on your phone, no app store needed",
			"Export GPX to your watch, head unit, or computer",
			"Import GPX from friends, Strava, or anywhere else",
		],
		phoneCaption: "the real mobile app, not a mockup",
	},
	surface: {
		eyebrow: "Surface intelligence",
		title: [{ text: "Know what you're " }, { text: "actually", accent: true }, { text: " stepping on." }],
		body: "Routess breaks every route into surface segments, so you'll never accidentally take a road bike down a goat track again. Probably.",
		buckets: [
			{ name: "Paved", pct: 46, desc: "Tarmac, asphalt, smooth concrete." },
			{ name: "Compacted", pct: 13, desc: "Hard-packed gravel, cinder paths." },
			{ name: "Unpaved", pct: 38, desc: "Forest tracks, dirt, sand." },
			{ name: "Path", pct: 3, desc: "Single-track footpaths, trails." },
		],
		elevationLabel: "Elevation profile",
		elevationStats: "Hallerbos walk · 5.4 km · ↑ 68 m",
	},
	routegen: {
		eyebrow: "Coming soon · Route generation",
		title: [{ text: "Don't know where to go? " }, { text: "Ask.", accent: true }],
		body: "Soon you'll type what you feel like doing, and Routess will turn it into a real route, with surfaces you'd actually want to ride or run on. In the works, not live yet.",
		bullets: [
			"Loop or A→B, your call",
			"Target distance, give or take",
			"Surface preference: paved · mixed · unpaved",
			"Avoids busy roads where it can",
		],
		promptLabel: "Prompt",
		prompts: [
			"30 km loop, mostly gravel, low traffic",
			"Easy 5 km run near the river",
			"Hilly cycle ride, finish at a café",
			"Two-day hike, A→B, paths only",
		],
		generateBtn: "✨ Generate route",
	},
	sharing: {
		eyebrow: "Library & sharing",
		title: "Your routes, found again.",
		body: "Save what you plan. Share a link, drop a GPX, or open a friend's route in one tap. The library stays organised even when you forget where you went.",
		myRoutes: "My routes",
		filters: { all: "All", run: "Run", cycle: "Cycle" },
		shareTitle: "Share route",
		shareSubtitle: "Sint-Amands loop · 31.8 km",
		copy: "copy",
		comingSoonEyebrow: "Coming soon",
		comingSoonTitle: "Community routes",
		comingSoonBody:
			'Browse routes others have plotted in your area, with photos, surface data, and an "actually fun" rating.',
		routes: [
			{ name: "Sint-Amands loop", dist: "31.8 km", time: "1.9 h", elev: "32 m" },
			{ name: "River dawn run", dist: "8.2 km", time: "0.8 h", elev: "12 m" },
			{ name: "Forest gravel grind", dist: "62.4 km", time: "3.2 h", elev: "320 m" },
			{ name: "Sunday slow walk", dist: "4.1 km", time: "0.9 h", elev: "8 m" },
		],
	},
	pricing: {
		eyebrow: "Pricing",
		title: [{ text: "Start free. " }, { text: "Go further when you want to.", accent: true }],
		body: "The whole planner is free, forever. A Pro plan with the heavier extras is planned for the people who plan a lot.",
		freeName: "Free",
		freeTagline: "For anyone who just wants to plan a route.",
		freePrice: "€0",
		freePeriod: "/ forever",
		freePerks: [
			"Unlimited route planning",
			"Run · Cycle · Walk modes",
			"GPX import & export",
			"Save unlimited routes",
			"Public route sharing",
			"Surface & elevation data",
		],
		freeCta: "Plan a route",
		proName: "Pro",
		proTagline: "Planned, for the people who plan every weekend.",
		proPrice: "Soon",
		proPeriod: "",
		proAlt: "pricing TBD",
		proPerks: [
			"Everything in Free",
			"Route generation",
			"Heatmaps & advanced layers",
			"Higher rate limits",
			"Priority support",
			"Early access to new features",
		],
		proCta: "Follow the roadmap",
		proBadge: "Coming soon",
		selfHostNote: "Or self-host it on your own infra, free, MIT, no strings attached.",
		selfHostLink: "self-host it",
	},
	openSource: {
		repo: "robbeverhelst/routess · MIT",
		title: "Built in the open. Yours to fork, host, or extend.",
		body: "An API, a CLI, a Helm chart, a Docker image, and source you can read. For the dev-curious, there's a separate page just for you.",
		cta: "For developers",
	},
	footer: {
		tagline: "A route planner for cyclists, runners, and hikers. Open source, free, and a little bit playful.",
		colProduct: {
			title: "Product",
			items: [
				{ label: "Planner", href: "https://app.routess.com" },
				{ label: "Library", href: "https://app.routess.com/routes" },
				{ label: "Roadmap", href: "https://github.com/robbeverhelst/routess/issues" },
			],
		},
		colOpen: {
			title: "Open",
			items: [
				{ label: "GitHub", href: "https://github.com/robbeverhelst/routess" },
				{ label: "API docs", href: "https://docs.routess.com/api-reference" },
				{ label: "Self-host", href: "/developers" },
			],
		},
		colMore: {
			title: "More",
			items: [
				{ label: "Docs", href: "https://docs.routess.com" },
				{ label: "Guides", href: "/guides" },
				{ label: "Compare", href: "/compare" },
				{ label: "Privacy", href: "/privacy" },
				{ label: "License (MIT)", href: "https://github.com/robbeverhelst/routess/blob/main/LICENSE" },
			],
		},
		copyright: "© 2026 routess · MIT license",
		madeWith: "made with map tiles & coffee · Belgium",
	},
	dev: {
		hero: {
			chip: "Open source · MIT · self-hostable",
			title: [{ text: "Built for " }, { text: "developers", accent: true }, { text: " who want to read the source." }],
			body: "Routess ships an API, a CLI, an OpenAPI spec, a Docker image, and a Helm chart. Run it on your laptop, deploy it to your cluster, embed it in your tools.",
			ctaDocs: "Read the docs",
			ctaGithub: "View on GitHub",
		},
		sections: [
			{
				eyebrow: "Public API",
				title: "Every action is an HTTP call.",
				body: "Routes, waypoints, library, exports. The web app uses the same API you do, with a typed OpenAPI client generated from the same spec.",
				bullets: [
					"REST + JSON, OpenAPI 3 spec",
					"Personal access tokens for non-browser clients",
					"Stable error protocol with machine-readable codes",
					"Generated TypeScript client",
				],
			},
			{
				eyebrow: "CLI",
				title: "Routess in your terminal.",
				body: "A small CLI for the operations you actually do: list routes, inspect one, rename it, manage your tokens. JSON output mode and stable exit codes for scripting.",
				bullets: [
					"`routess routes list`",
					"`routess routes get <id>`",
					'`routess routes update <id> --name "..."`',
					"`routess auth whoami`",
				],
			},
			{
				eyebrow: "Self-host",
				title: "Your infra, your data.",
				body: "A Helm chart, a Docker Compose file, a deny-all-by-default network policy baseline. Bring your own Postgres, Mapbox/provider keys, OAuth client. No phone-home.",
				bullets: [
					"Helm chart at `charts/routess`",
					"Docker images on GHCR",
					"Postgres + Valhalla + Mapbox required",
					"GDPR-safe defaults",
				],
			},
		],
	},
	routePage: {
		eyebrow: "Shared route",
		activities: { run: "running route", cycle: "cycling route", walk: "walking route", route: "route" },
		stats: { distance: "Distance", elevation: "Elevation gain", duration: "Estimated time" },
		openInApp: "Open in routess",
		downloadGpx: "Download GPX",
		planYourOwn: "Plan your own route",
		about: "About this route",
		mapAlt: "Map of the route",
		summaryTemplate:
			"A {distance} {activity} with {elevation} m of climbing. View it, edit it, and export the GPX free with routess.",
		byAuthor: "by {name}",
	},
	profilePage: {
		eyebrow: "routess profile",
		stats: { routes: "Public routes", distance: "Total distance", elevation: "Elevation gain", followers: "Followers" },
		routesTitle: "Public routes",
		followInApp: "Follow on routess",
		planYourOwn: "Plan your own route",
		summaryTemplate: "{name} shares {count} public routes on routess, covering {distance} in total.",
	},
	meta: {
		landing: {
			title: "routess · plan routes for running, cycling & hiking",
			description:
				"Pin it, plan it, move. A free, open-source route planner that actually follows the trail. Run it, ride it, walk it, then share it.",
		},
		developers: {
			title: "routess for developers · API, CLI, self-host",
			description:
				"Open-source, MIT-licensed route planner with a public API, a CLI, a Helm chart, and a Docker image. Read the source, deploy it, fork it.",
		},
	},
};
