import type { Dict } from "./types";

export const en: Dict = {
	nav: {
		plan: "Plan",
		features: "Features",
		community: "Community",
		pricing: "Pricing",
		forDevelopers: "For developers",
		planRoute: "Plan a route",
		home: "Home",
		docs: "Docs",
		github: "GitHub",
		star: "Star",
		readDocs: "Read docs",
	},
	hero: {
		chip: "Run · Cycle · Walk",
		headlineLines: [{ text: "Pin it." }, { text: "Plan it." }, { text: "Move.", accent: true }],
		body: "Drop pins. Get a route that actually follows the trail. Run it, ride it, walk it, then share it with anyone.",
		ctaPrimary: "Plan your first route",
		ctaSecondary: "See features",
		bullets: ["Free forever", "No account to plan", "GPX in & out"],
		mode: { run: "Run", cycle: "Cycle", walk: "Walk" },
		statThisRoute: "This route",
		statDist: "dist",
		statElev: "elev",
		statTime: "time",
	},
	marquee: [
		"🏃 Sint-Amands loop · 28.5 km",
		"🚴 Forest gravel grind · 62 km",
		"🥾 Lippelobos out-and-back · 12 km",
		"🏃 River dawn run · 8.2 km",
		"🚴 Café-to-café cruise · 41 km",
		"🥾 Sunday slow walk · 4.1 km",
		"🏃 Hill repeats · 6 km",
		"🚴 Tour de Puurs · 84 km",
	],
	planner: {
		eyebrow: "Live demo · no signup",
		title: [{ text: "Drop pins. " }, { text: "Get a route.", accent: true }],
		body: "A tiny version of the real planner. Click anywhere on the map to add a waypoint, the path snaps along the way.",
		mode: "Mode",
		surface: "Surface",
		surfaces: { paved: "paved", mixed: "mixed", unpaved: "unpaved" },
		modes: { run: "Run", cycle: "Cycle", walk: "Walk" },
		total: "Total",
		computedLive: "computed live",
		openInApp: "Open in app",
		hint: "tip: tap and hold a pin to drag in the real app",
		clickHint: "click to add waypoint",
		reset: "Reset",
		waypoints: "waypoints",
	},
	modes: {
		eyebrow: "For every kind of moving",
		title: "Run it. Ride it. Walk it.",
		body: "One planner that actually understands the difference between a cycle path, a single track, and a sidewalk, and routes you accordingly.",
		items: [
			{
				mode: "Run",
				copy: "Pace, splits, surface bias for soft trails. Loops or A→B.",
				stat: "5'30/km",
				statLabel: "avg pace",
			},
			{
				mode: "Cycle",
				copy: "Hills, gravel preferences, distance targets up to 300 km.",
				stat: "28.5 km",
				statLabel: "today's plan",
			},
			{
				mode: "Walk",
				copy: "Footpaths first. Wheelchair-friendly toggle for any route.",
				stat: "5.7 h",
				statLabel: "estimated",
			},
		],
	},
	surface: {
		eyebrow: "Surface intelligence",
		title: [{ text: "Know what you're " }, { text: "actually", accent: true }, { text: " stepping on." }],
		body: "Routess breaks every route into surface segments, so you'll never accidentally take a road bike down a goat track again. Probably.",
		buckets: [
			{ name: "Paved", pct: 46, desc: "Tarmac, asphalt, smooth concrete." },
			{ name: "Compacted", pct: 13, desc: "Hard-packed gravel, cinder paths." },
			{ name: "Unpaved", pct: 38, desc: "Forest tracks, dirt, sand." },
			{ name: "Path", pct: 3, desc: "Single-track footpaths, trails." },
		],
		elevationLabel: "Elevation profile",
		elevationStats: "↑ 46 m · ↓ 44 m",
	},
	routegen: {
		eyebrow: "Route generation",
		title: [{ text: "Don't know where to go? " }, { text: "Ask.", accent: true }],
		body: "Type what you feel like doing. Routess turns it into a real route, with surfaces you'd actually want to ride or run on.",
		bullets: [
			"Loop or A→B, your call",
			"Target distance, give or take",
			"Surface preference: paved · mixed · unpaved",
			"Paths-only or wheel-friendly toggles",
		],
		promptLabel: "Prompt",
		prompts: [
			"30 km loop, mostly gravel, low traffic",
			"Easy 5 km run near the river",
			"Hilly cycle ride, finish at a café",
			"Two-day hike, A→B, paths only",
		],
		generateBtn: "✨ Generate route",
	},
	sharing: {
		eyebrow: "Library & sharing",
		title: "Your routes, found again.",
		body: "Save what you plan. Share a link, drop a GPX, or open a friend's route in one tap. The library stays organised even when you forget where you went.",
		myRoutes: "My routes",
		filters: { all: "All", run: "Run", cycle: "Cycle" },
		shareTitle: "Share route",
		shareSubtitle: "Sint-Amands loop · 28.5 km",
		copy: "copy",
		comingSoonEyebrow: "Coming soon",
		comingSoonTitle: "Community routes",
		comingSoonBody:
			'Browse routes others have plotted in your area, with photos, surface data, and an "actually fun" rating.',
		routes: [
			{ name: "Sint-Amands loop", dist: "28.5 km", time: "5.7 h", elev: "46 m" },
			{ name: "River dawn run", dist: "8.2 km", time: "0.8 h", elev: "12 m" },
			{ name: "Forest gravel grind", dist: "62.4 km", time: "3.2 h", elev: "320 m" },
			{ name: "Sunday slow walk", dist: "4.1 km", time: "0.9 h", elev: "8 m" },
		],
	},
	pricing: {
		eyebrow: "Pricing",
		title: [{ text: "Start free. " }, { text: "Go further when you want to.", accent: true }],
		body: "The whole planner is free, forever. Pro adds the heavier features, AI generation, advanced layers, priority support, for the people who plan a lot.",
		freeName: "Free",
		freeTagline: "For anyone who just wants to plan a route.",
		freePrice: "€0",
		freePeriod: "/ forever",
		freePerks: [
			"Unlimited route planning",
			"Run · Cycle · Walk modes",
			"GPX import & export",
			"Save unlimited routes",
			"Public route sharing",
			"Surface & elevation data",
		],
		freeCta: "Plan a route",
		proName: "Pro",
		proTagline: "For the people who plan every weekend.",
		proPrice: "€4",
		proPeriod: "/ month",
		proAlt: "or €40/yr",
		proPerks: [
			"Everything in Free",
			"AI route generation",
			"Heatmaps & advanced layers",
			"Higher generation rate limits",
			"Priority support",
			"Early access to new features",
		],
		proCta: "Get Pro",
		proBadge: "Most popular",
		selfHostNote: "Or self-host it on your own infra, free, MIT, no strings attached.",
		selfHostLink: "self-host it",
	},
	openSource: {
		repo: "robbeverhelst/routess · MIT",
		title: "Built in the open. Yours to fork, host, or extend.",
		body: "An API, a CLI, a Helm chart, a Docker image, and source you can read. For the dev-curious, there's a separate page just for you.",
		cta: "For developers",
	},
	footer: {
		tagline: "A route planner for cyclists, runners, and hikers. Open source, free, and a little bit playful.",
		colProduct: {
			title: "Product",
			items: [
				{ label: "Planner", href: "https://app.routess.com" },
				{ label: "Library", href: "https://app.routess.com/routes" },
				{ label: "Roadmap", href: "https://github.com/robbeverhelst/routess/issues" },
			],
		},
		colOpen: {
			title: "Open",
			items: [
				{ label: "GitHub", href: "https://github.com/robbeverhelst/routess" },
				{ label: "API docs", href: "https://docs.routess.com/api-reference" },
				{ label: "Self-host", href: "/developers" },
			],
		},
		colMore: {
			title: "More",
			items: [
				{ label: "Docs", href: "https://docs.routess.com" },
				{ label: "Privacy", href: "/privacy" },
				{ label: "License (MIT)", href: "https://github.com/robbeverhelst/routess/blob/main/LICENSE" },
			],
		},
		copyright: "© 2026 routess · MIT license",
		madeWith: "made with map tiles & coffee · Belgium",
		mastodon: "Mastodon",
	},
	dev: {
		hero: {
			chip: "Open source · MIT · self-hostable",
			title: [{ text: "Built for " }, { text: "developers", accent: true }, { text: " who want to read the source." }],
			body: "Routess ships an API, a CLI, an OpenAPI spec, a Docker image, and a Helm chart. Run it on your laptop, deploy it to your cluster, embed it in your tools.",
			ctaDocs: "Read the docs",
			ctaGithub: "View on GitHub",
		},
		sections: [
			{
				eyebrow: "Public API",
				title: "Every action is an HTTP call.",
				body: "Routes, waypoints, generation, library, exports. The web app uses the same API you do, with a typed OpenAPI client generated from the same spec.",
				bullets: [
					"REST + JSON, OpenAPI 3 spec",
					"Personal access tokens for non-browser clients",
					"Stable error protocol with machine-readable codes",
					"Generated TypeScript client",
				],
			},
			{
				eyebrow: "CLI",
				title: "Routess in your terminal.",
				body: "A small CLI for the operations you actually do: list routes, export GPX, generate a loop, inspect a draft. JSON output mode and stable exit codes for scripting.",
				bullets: [
					"`routess routes list`",
					"`routess routes export <id> --format gpx`",
					"`routess generate --loop --distance 30km`",
					"`routess draft inspect`",
				],
			},
			{
				eyebrow: "Self-host",
				title: "Your infra, your data.",
				body: "A Helm chart, a Docker Compose file, a deny-all-by-default network policy baseline. Bring your own Postgres, Mapbox/provider keys, OAuth client. No phone-home.",
				bullets: [
					"Helm chart at `charts/routess`",
					"Docker images on GHCR",
					"Postgres + Valhalla + Mapbox required",
					"GDPR-safe defaults",
				],
			},
		],
	},
	meta: {
		landing: {
			title: "routess · plan routes for running, cycling & hiking",
			description:
				"Pin it, plan it, move. A free, open-source route planner that actually follows the trail. Run it, ride it, walk it, then share it.",
		},
		developers: {
			title: "routess for developers · API, CLI, self-host",
			description:
				"Open-source, MIT-licensed route planner with a public API, a CLI, a Helm chart, and a Docker image. Read the source, deploy it, fork it.",
		},
	},
};
