import type { Dict } from "./types";

// Parallel rewrite, not a literal translation. The English page is for the
// international developer/cyclist audience; this Dutch page is the Belgian one.
// Tone: a little playful, a little dry, a little Belgian.
export const nl: Dict = {
	nav: {
		plan: "Plan",
		features: "Features",
		community: "Community",
		pricing: "Prijzen",
		forDevelopers: "Voor ontwikkelaars",
		planRoute: "Plan een route",
		home: "Home",
		docs: "Docs",
		github: "GitHub",
		star: "Star",
		readDocs: "Lees de docs",
	},
	hero: {
		chip: "Lopen · Fietsen · Wandelen",
		headlineLines: [{ text: "Prik het." }, { text: "Plan het." }, { text: "Ga.", accent: true }],
		body: "Plaats je punten, en je krijgt een route die effectief het pad volgt. Loop hem, fiets hem, wandel hem, en stuur hem door naar wie je maar wil.",
		ctaPrimary: "Plan je eerste route",
		ctaSecondary: "Bekijk features",
		bullets: ["Voor altijd gratis", "Geen account nodig om te plannen", "GPX in & uit"],
	},
	marquee: [
		"🏃 Sint-Amands lus · 31,8 km",
		"🚴 Bos- en grindrit · 62 km",
		"🥾 Lippelobos heen-en-terug · 12 km",
		"🏃 Schelde-ochtendloop · 8,2 km",
		"🚴 Café-naar-café cruise · 41 km",
		"🥾 Trage zondagswandeling · 4,1 km",
		"🏃 Heuveltjes · 6 km",
		"🚴 Tour de Puurs · 84 km",
	],
	planner: {
		eyebrow: "Live demo · zonder login",
		title: [{ text: "Prik wat punten. " }, { text: "Krijg een route.", accent: true }],
		body: "Een mini-versie van de echte planner. Klik ergens op de kaart om een waypoint toe te voegen, het pad volgt vanzelf.",
		mode: "Modus",
		modes: { run: "Lopen", cycle: "Fietsen", walk: "Wandelen" },
		total: "Totaal",
		computedLive: "live berekend",
		timeLabel: "tijd",
		openInApp: "Open in de app",
		hint: "tip: in de echte app kan je een punt vasthouden om hem te slepen",
		clickHint: "klik om een waypoint toe te voegen",
		reset: "Reset",
		waypoints: "waypoints",
	},
	mapStyles: {
		eyebrow: "Stijlen & thema's",
		title: [{ text: "Eén route. " }, { text: "Elke kaart.", accent: true }],
		body: "Streets voor de stad, outdoors voor hoogtelijnen en paden, satelliet om te checken of dat grind wel echt grind is. En elke stijl heeft een donker thema voor wie na zonsondergang plant.",
		items: [
			{ key: "streets", name: "Streets", desc: "Strak en vertrouwd" },
			{ key: "outdoors", name: "Outdoors", desc: "Hoogtelijnen, paden, terrein" },
			{ key: "satellite", name: "Satelliet", desc: "Zie wat er echt ligt" },
			{ key: "dark", name: "Donker thema", desc: "Elke stijl, lichten uit" },
		],
	},
	outside: {
		eyebrow: "Mee naar buiten",
		title: [{ text: "Plan aan je bureau. " }, { text: "Volg hem onderweg.", accent: true }],
		body: "Dezelfde planner werkt op je telefoon, dus de route die je zondagavond uitstippelde zit maandagochtend gewoon in je zak. En je routes zitten nooit vast.",
		bullets: [
			"Werkt als app op je telefoon, geen app store nodig",
			"Exporteer GPX naar je horloge, fietscomputer of computer",
			"Importeer GPX van vrienden, Strava, of waar dan ook",
		],
		phoneCaption: "de echte mobiele app, geen mockup",
	},
	surface: {
		eyebrow: "Ondergrond-intelligentie",
		title: [{ text: "Weet waarop je " }, { text: "echt", accent: true }, { text: " stapt." }],
		body: "Routess hakt elke route op in stukjes ondergrond, zodat je nooit meer per ongeluk met je koersfiets in een geitenpad belandt. Waarschijnlijk.",
		buckets: [
			{ name: "Verhard", pct: 46, desc: "Asfalt, beton, gladde wegen." },
			{ name: "Gecompacteerd", pct: 13, desc: "Aangedrukt grind, sintelpaden." },
			{ name: "Onverhard", pct: 38, desc: "Bospaden, aarde, zand." },
			{ name: "Pad", pct: 3, desc: "Smalle wandelpaadjes." },
		],
		elevationLabel: "Hoogteprofiel",
		elevationStats: "Hallerbos-wandeling · 5,4 km · ↑ 68 m",
	},
	routegen: {
		eyebrow: "Komt eraan · Route-generatie",
		title: [{ text: "Geen idee waarheen? " }, { text: "Vraag het.", accent: true }],
		body: "Binnenkort typ je wat je wil doen, en maakt Routess er een echte route van, met een ondergrond waar je effectief op wil rijden of lopen. In de maak, nog niet live.",
		bullets: [
			"Lus of A→B, jij kiest",
			"Doel-afstand, ongeveer",
			"Voorkeur ondergrond: verhard · gemengd · onverhard",
			"Mijdt drukke wegen waar het kan",
		],
		promptLabel: "Prompt",
		prompts: [
			"Lus van 30 km, vooral grind, weinig verkeer",
			"Rustige looprondje van 5 km langs de Schelde",
			"Heuvelachtige fietsrit, eindigt bij een café",
			"Tweedaagse wandeling, A→B, alleen paden",
		],
		generateBtn: "✨ Genereer route",
	},
	sharing: {
		eyebrow: "Bibliotheek & delen",
		title: "Je routes, weer terug.",
		body: "Bewaar wat je plant. Stuur een link, een GPX, of open de route van een vriend met één tap. De bibliotheek blijft op orde, ook als jij niet meer weet waar je liep.",
		myRoutes: "Mijn routes",
		filters: { all: "Alles", run: "Lopen", cycle: "Fietsen" },
		shareTitle: "Deel route",
		shareSubtitle: "Sint-Amands lus · 31,8 km",
		copy: "kopieer",
		comingSoonEyebrow: "Komt eraan",
		comingSoonTitle: "Community-routes",
		comingSoonBody:
			'Bekijk routes die anderen in jouw buurt geplot hebben, met foto\'s, ondergrond-data, en een "echt-leuk"-score.',
		routes: [
			{ name: "Sint-Amands lus", dist: "31,8 km", time: "1,9 u", elev: "32 m" },
			{ name: "Schelde-ochtendloop", dist: "8,2 km", time: "0,8 u", elev: "12 m" },
			{ name: "Bos- en grindrit", dist: "62,4 km", time: "3,2 u", elev: "320 m" },
			{ name: "Trage zondagswandeling", dist: "4,1 km", time: "0,9 u", elev: "8 m" },
		],
	},
	pricing: {
		eyebrow: "Prijzen",
		title: [{ text: "Begin gratis. " }, { text: "Ga verder als je dat wil.", accent: true }],
		body: "De volledige planner is gratis, voor altijd. Een Pro-plan met het zwaardere werk is gepland voor de mensen die élk weekend plannen.",
		freeName: "Gratis",
		freeTagline: "Voor wie gewoon een route wil plannen.",
		freePrice: "€0",
		freePeriod: "/ voor altijd",
		freePerks: [
			"Onbeperkt routes plannen",
			"Loop · Fiets · Wandel modi",
			"GPX import & export",
			"Onbeperkt routes opslaan",
			"Publieke route-deling",
			"Ondergrond- & hoogtedata",
		],
		freeCta: "Plan een route",
		proName: "Pro",
		proTagline: "Gepland, voor wie elk weekend plant.",
		proPrice: "Binnenkort",
		proPeriod: "",
		proAlt: "prijs nog niet bepaald",
		proPerks: [
			"Alles uit Gratis",
			"Route-generatie",
			"Heatmaps & geavanceerde lagen",
			"Hogere limieten",
			"Prioritaire support",
			"Vroege toegang tot nieuwe features",
		],
		proCta: "Volg de roadmap",
		proBadge: "Komt eraan",
		selfHostNote: "Of host het zelf op je eigen infra, gratis, MIT, geen voorwaarden.",
		selfHostLink: "host het zelf",
	},
	openSource: {
		repo: "robbeverhelst/routess · MIT",
		title: "Open gebouwd. Forken, hosten, of uitbreiden, jouw keuze.",
		body: "Een API, een CLI, een Helm chart, een Docker image, en broncode die je kan lezen. Voor de dev-nieuwsgierigen is er een aparte pagina.",
		cta: "Voor ontwikkelaars",
	},
	footer: {
		tagline: "Een route-planner voor fietsers, lopers en wandelaars. Open source, gratis, en een tikje speels.",
		colProduct: {
			title: "Product",
			items: [
				{ label: "Planner", href: "https://app.routess.com" },
				{ label: "Bibliotheek", href: "https://app.routess.com/routes" },
				{ label: "Roadmap", href: "https://github.com/robbeverhelst/routess/issues" },
			],
		},
		colOpen: {
			title: "Open",
			items: [
				{ label: "GitHub", href: "https://github.com/robbeverhelst/routess" },
				{ label: "API-docs", href: "https://docs.routess.com/api-reference" },
				{ label: "Zelf hosten", href: "/developers" },
			],
		},
		colMore: {
			title: "Meer",
			items: [
				{ label: "Docs", href: "https://docs.routess.com" },
				{ label: "Gidsen", href: "/gids" },
				{ label: "Vergelijk", href: "/vergelijk" },
				{ label: "Privacy", href: "/privacy" },
				{ label: "Licentie (MIT)", href: "https://github.com/robbeverhelst/routess/blob/main/LICENSE" },
			],
		},
		copyright: "© 2026 routess · MIT-licentie",
		madeWith: "gemaakt met kaarttegels & koffie · België",
	},
	dev: {
		hero: {
			chip: "Open source · MIT · zelf te hosten",
			title: [
				{ text: "Gebouwd voor " },
				{ text: "ontwikkelaars", accent: true },
				{ text: " die de broncode willen lezen." },
			],
			body: "Routess heeft een API, een CLI, een OpenAPI-spec, een Docker image, en een Helm chart. Draai het op je laptop, zet het in je cluster, embed het in je tools.",
			ctaDocs: "Lees de docs",
			ctaGithub: "Bekijk op GitHub",
		},
		sections: [
			{
				eyebrow: "Publieke API",
				title: "Elke actie is een HTTP-call.",
				body: "Routes, waypoints, bibliotheek, exports. De web-app gebruikt dezelfde API als jij, met een getypte OpenAPI-client uit dezelfde spec.",
				bullets: [
					"REST + JSON, OpenAPI 3-spec",
					"Personal access tokens voor niet-browser clients",
					"Stabiel error-protocol met machine-leesbare codes",
					"Gegenereerde TypeScript-client",
				],
			},
			{
				eyebrow: "CLI",
				title: "Routess in je terminal.",
				body: "Een kleine CLI voor wat je effectief doet: routes lijsten, er één bekijken, hernoemen, je tokens beheren. JSON-output en stabiele exit-codes voor scripts.",
				bullets: [
					"`routess routes list`",
					"`routess routes get <id>`",
					'`routess routes update <id> --name "..."`',
					"`routess auth whoami`",
				],
			},
			{
				eyebrow: "Zelf hosten",
				title: "Jouw infra, jouw data.",
				body: "Een Helm chart, een Docker Compose file, een deny-all-by-default netwerkbeleid. Eigen Postgres, Mapbox-keys, OAuth client. Geen phone-home.",
				bullets: [
					"Helm chart in `charts/routess`",
					"Docker images op GHCR",
					"Postgres + Valhalla + Mapbox vereist",
					"GDPR-veilige defaults",
				],
			},
		],
	},
	meta: {
		landing: {
			title: "routess · plan routes om te lopen, fietsen & wandelen",
			description:
				"Prik het, plan het, ga. Een gratis, open-source route-planner die effectief het pad volgt. Loop hem, fiets hem, wandel hem, en deel hem.",
		},
		developers: {
			title: "routess voor ontwikkelaars · API, CLI, zelf hosten",
			description:
				"Open-source, MIT-gelicentieerde route-planner met publieke API, CLI, Helm chart en Docker image. Lees de broncode, deploy hem, fork hem.",
		},
	},
};
