{{- if .Values.serviceAccount.web.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "routess.web.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "routess.web.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.web.automountServiceAccountToken | default false }}
{{- end }}
---
{{- if .Values.serviceAccount.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "routess.api.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "routess.api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.api.automountServiceAccountToken | default false }}
{{- end }}
---
{{- if .Values.serviceAccount.docs.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "routess.docs.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "routess.docs.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.docs.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.docs.automountServiceAccountToken | default false }}
{{- end }}
---
{{- if .Values.serviceAccount.landing.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "routess.landing.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "routess.landing.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.landing.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.landing.automountServiceAccountToken | default false }}
{{- end }}
