/**
 * Tilted "app screenshot" for the hero. Renders a real capture of the planner
 * UI, regenerated by `bun run screenshots`. Imported statically so Next emits a
 * blurDataURL placeholder (instant low-res preview, no blank pop-in) and the
 * intrinsic dimensions. The whole thing is CSS-perspective-tilted in
 * globals.css so it reads as a 3D product shot bleeding off the right edge of
 * the hero column.
 */
import Image from "next/image";
import mobileShot from "../../public/app-mobile.webp";
import heroShot from "../../public/hero-screenshot.webp";

export function HeroAppScreenshot() {
	return (
		<div className="hero-screenshot-wrap" aria-hidden="true">
			{/* Desktop: the tilted planner capture bleeding off the column. */}
			<div className="hero-screenshot">
				<Image
					src={heroShot}
					alt=""
					priority
					placeholder="blur"
					sizes="(max-width: 900px) 1px, 920px"
					style={{ width: "100%", height: "100%", objectFit: "cover" }}
				/>
			</div>
			{/* Mobile: the full mobile-layout capture in a phone frame, instead
			   of an illegible crop of the desktop UI. */}
			<div className="hero-phone">
				<div className="hero-phone-frame">
					<Image
						src={mobileShot}
						alt=""
						placeholder="blur"
						sizes="(max-width: 900px) 240px, 1px"
						style={{ width: "100%", height: "auto", display: "block", borderRadius: 26 }}
					/>
				</div>
			</div>
		</div>
	);
}
