/**
 * Tilted "app screenshot" for the hero. Renders a real capture of the planner
 * UI, regenerated by `bun run screenshots`.
 *
 * Served as a plain static asset instead of through next/image: the captures
 * are already encoded at exactly the size they render at, so the optimizer only
 * added a round trip to origin. `/_next/image` responses carry `Vary: Accept`
 * and are never edge-cached (cf-cache-status: DYNAMIC), while
 * `/_next/static/media/*` is immutable and does cache at the edge.
 *
 * Each container uses <picture> so the breakpoint that hides it resolves to a
 * blank pixel and downloads nothing. Preloads are media-scoped for the same
 * reason. The tilt itself lives in globals.css.
 */
import mobileShot from "../../public/app-mobile.webp";
import heroShot from "../../public/hero-screenshot.webp";

const DESKTOP = "(min-width: 901px)";
const MOBILE = "(max-width: 900px)";

// 1x1 transparent GIF: what the hidden breakpoint resolves to.
const BLANK = "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";

function blurStyle(blurDataURL: string | undefined) {
	if (!blurDataURL) return undefined;
	return {
		backgroundImage: `url("${blurDataURL}")`,
		backgroundSize: "cover",
		backgroundPosition: "50% 50%",
	};
}

export function HeroAppScreenshot() {
	return (
		<div className="hero-screenshot-wrap" aria-hidden="true">
			<link rel="preload" as="image" href={heroShot.src} media={DESKTOP} fetchPriority="high" />
			<link rel="preload" as="image" href={mobileShot.src} media={MOBILE} fetchPriority="high" />

			{/* Desktop: the tilted planner capture bleeding off the column. */}
			<div className="hero-screenshot">
				<picture>
					<source media={MOBILE} srcSet={BLANK} />
					<img
						src={heroShot.src}
						width={heroShot.width}
						height={heroShot.height}
						alt=""
						fetchPriority="high"
						decoding="async"
						style={{
							width: "100%",
							height: "100%",
							objectFit: "cover",
							...blurStyle(heroShot.blurDataURL),
						}}
					/>
				</picture>
			</div>

			{/* Mobile: the full mobile-layout capture in a phone frame, instead
			   of an illegible crop of the desktop UI. */}
			<div className="hero-phone">
				<div className="hero-phone-frame">
					<picture>
						<source media={DESKTOP} srcSet={BLANK} />
						<img
							src={mobileShot.src}
							width={mobileShot.width}
							height={mobileShot.height}
							alt=""
							fetchPriority="high"
							decoding="async"
							style={{
								width: "100%",
								height: "auto",
								display: "block",
								borderRadius: 26,
								...blurStyle(mobileShot.blurDataURL),
							}}
						/>
					</picture>
				</div>
			</div>
		</div>
	);
}
