import { expect, test } from "@playwright/test";
import { installE2EUiState, loginViaEmailUI } from "../support/auth";
import { truncateDb } from "../support/db";
import { getRouteDraft, waitForBridge, waitForRouteCalculated } from "../support/routessApi";
import { rightClickAtMapPixel } from "../support/stable-map";

// Share link encode/decode round-trip. The share URL is generated by the
// editor and contains compressed waypoint data; opening it (even unauthenticated)
// hydrates a fresh RouteDraft from the URL parameter. See `lib/shareUtils.ts`.

async function loginAndWaitForRealMap(
	page: Parameters<typeof loginViaEmailUI>[0],
	request: Parameters<typeof loginViaEmailUI>[1],
	email: string,
) {
	await loginViaEmailUI(page, request, email);
	await page.locator("canvas.mapboxgl-canvas").waitFor({ state: "visible", timeout: 30_000 });
	await waitForBridge(page);
}

async function addDirectWaypointViaMapContextMenu(
	page: Parameters<typeof rightClickAtMapPixel>[0],
	dx: number,
	dy: number,
) {
	await rightClickAtMapPixel(page, dx, dy);
	await page.getByRole("button", { name: /add direct waypoint/i }).click();
}

test.describe("share link with real Mapbox", () => {
	test.beforeEach(async () => {
		await truncateDb();
	});

	test("generated share URL hydrates a fresh RouteDraft in a clean context", async ({ browser, page, request }) => {
		await loginAndWaitForRealMap(page, request, "sharer@test.local");

		await addDirectWaypointViaMapContextMenu(page, 250, 250);
		await addDirectWaypointViaMapContextMenu(page, 320, 250);
		await addDirectWaypointViaMapContextMenu(page, 390, 250);
		await waitForRouteCalculated(page);

		const original = await getRouteDraft(page);
		const shareResult = await page.evaluate(() => {
			const api = window.__routess;
			if (!api) throw new Error("__routess bridge not present");
			return api.editor.buildShareUrl();
		});
		expect(shareResult.success).toBe(true);
		expect(shareResult.url).toBeTruthy();

		const otherContext = await browser.newContext();
		const otherPage = await otherContext.newPage();
		await installE2EUiState(otherPage);
		await otherPage.goto(shareResult.url ?? "/");
		await otherPage.getByRole("button", { name: /continue without an account/i }).click();
		await otherPage.waitForFunction(() => typeof window.__routess !== "undefined", undefined, { timeout: 30_000 });

		const hydrated = await otherPage.evaluate(() => {
			const api = window.__routess;
			if (!api) throw new Error("__routess bridge not present");
			const s = api.getRouteDraft();
			return s.waypoints.map((w) => ({ coord: w.coord, type: w.type }));
		});

		expect(hydrated).toEqual(original.waypoints);
		await otherContext.close();
	});

	test("buildShareUrl on an empty draft fails clearly", async ({ page, request }) => {
		await loginAndWaitForRealMap(page, request, "empty-share@test.local");

		const result = await page.evaluate(() => {
			const api = window.__routess;
			if (!api) throw new Error("__routess bridge not present");
			return api.editor.buildShareUrl();
		});
		expect(result.success).toBe(false);
	});
});
