apiVersion: v2
name: routess
description: Routess - route planning application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Robbe Verhelst
    url: https://github.com/robbeverhelst
