name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "charts/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "charts/**"

jobs:
  test:
    runs-on: arc-maps
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/setup-node@v6
        with:
          node-version: "20"

      - uses: actions/cache@v5
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/*/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-

      - run: bun install

      - name: Format & lint
        run: bunx biome check .

      - name: Type-check
        run: bun run --filter '*' check-types

      - name: Test
        run: bun run --filter './apps/web' --filter './packages/*' test

      - name: Build
        run: bun run --filter './packages/*' build && bun run --filter './apps/*' build

  release:
    needs: test
    runs-on: arc-maps
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/setup-node@v6
        with:
          node-version: "20"

      - run: bun install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory /home/runner/_work/maps/maps
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          bunx semantic-release
